#ifndef _ARXPORT__ACADI_I_
#define _ARXPORT__ACADI_I_ 1

#include "..\inc\icad_i.c"

// IIDs:

#define IID_IAcadPoint							IID_IIcadPoint
#define IID_IAcadPoints							IID_IIcadPoints
#define IID_IAcadVector							IID_IIcadVector
#define IID_IAcadMatrix							IID_IIcadMatrix
#define IID_IAcadLibrary						IID_IIcadLibrary
#define IID_IAcadUtility						IID_IIcadUtility
#define IID_IAcadHyperlinks						IID_IIcadHyperlinks
#define IID_IAcadHyperlink						IID_IIcadHyperlink
#define IID_IAcadAcCmColor						IID_IIcadAcCmColor
#define IID_IAcadPlotterPen						IID_IIcadPlotterPen
#define IID_IAcadPlotterPens					IID_IIcadPlotterPens
#define IID_IAcadPlotProperties					IID_IIcadPlotProperties
#define IID_IAcadPlotManager					IID_IIcadPlotManager
#define IID_IAcadPlotRegManager					IID_IIcadPlotRegManager
#define IID_IAcadMenuBar						IID_IIcadMenuBar
#define IID_IAcadMenuGroups						IID_IIcadMenuGroups
#define IID_IAcadMenuGroup						IID_IIcadMenuGroup
#define IID_IAcadPopupMenus						IID_IIcadPopupMenus
#define IID_IAcadPopupMenu						IID_IIcadPopupMenu
#define IID_IAcadPopupMenuItem					IID_IIcadPopupMenuItem
#define IID_IAcadToolbars						IID_IIcadToolbars
#define IID_IAcadToolbar						IID_IIcadToolbar
#define IID_IAcadToolbarItem					IID_IIcadToolbarItem
#define IID_IAcadDocuments						IID_IIcadDocuments
#define IID_IAcadWindows						IID_IIcadWindows
#define IID_IAcadWindow							IID_IIcadWindow
#define IID_IAcadApplication					IID_IIcadApplication
#define DIID__DAcadApplicationEvents			DIID_IZwcadApplicationEvents //?
#define IID_IAcadWorkspace						IID_IIcadWorkspace //?
#define DIID__AcadWorkspaceEvents				DIID__IcadWorkspaceEvents //?
#define IID_IAcadApplicationPreferences			IID_IIcadApplicationPreferences
#define IID_IAcadGroups							IID_IIcadGroups
#define IID_IAcadDbItem							IID_IIcadDbItem
#define IID_IAcadGroup							IID_IIcadGroup
#define IID_IAcadState							IID_IIcadState
#define IID_IAcadXRecord						IID_IIcadXRecord
#define IID_IAcadDictionary						IID_IIcadDictionary
#define IID_IAcadDictionaries					IID_IIcadDictionaries
#define IID_IAcadPlotConfiguration				IID_IIcadPlotConfiguration
#define IID_IAcadPlotConfigurations				IID_IIcadPlotConfigurations
#define IID_IAcadLayout							IID_IIcadLayout
#define IID_IAcadLayouts						IID_IIcadLayouts
#define IID_IAcadPlot							IID_IIcadPlot
#define IID_IAcadTableItem						IID_IIcadTableItem
#define IID_IAcadRegisteredApplication			IID_IIcadRegisteredApplication
#define IID_IAcadRegisteredApplications			IID_IIcadRegisteredApplications
#define IID_IAcadEntities						IID_IIcadEntities
#define IID_IAcadBlock							IID_IIcadBlock
#define IID_IAcadBlocks							IID_IIcadBlocks
#define IID_IAcadDimensionStyle					IID_IIcadDimensionStyle
#define IID_IAcadDimensionStyles				IID_IIcadDimensionStyles
#define IID_IAcadLayer							IID_IIcadLayer
#define IID_IAcadLayers							IID_IIcadLayers
#define IID_IAcadLinetype						IID_IIcadLinetype
#define IID_IAcadLinetypes						IID_IIcadLinetypes
#define IID_IAcadTextStyle						IID_IIcadTextStyle
#define IID_IAcadTextStyles						IID_IIcadTextStyles
#define IID_IAcadUserCoordSystem				IID_IIcadUserCoordSystem
#define IID_IAcadUserCoordSystems				IID_IIcadUserCoordSystems
#define IID_IAcadView							IID_IIcadView
#define IID_IAcadViews							IID_IIcadViews
#define IID_IAcadViewport						IID_IIcadViewport
#define IID_IAcadViewports						IID_IIcadViewports
#define IID_IAcadSelectionSet					IID_IIcadSelectionSet
#define IID_IAcadSelectionSets					IID_IIcadSelectionSets
#define IID_IAcadSummaryInfo					IID_IIcadSummaryInfo
#define IID_IAcadSortentsTable					IID_IIcadSortentsTable
#define IID_IAcadEntity							IID_IIcadEntity
#define IID_IAcad3DFace							IID_IIcad3DFace
#define IID_IAcad3DPoly							IID_IIcad3DPoly
#define IID_IAcadArc							IID_IIcadArc
#define IID_IAcadAttribute						IID_IIcadAttribute
#define IID_IAcadAttributeReference				IID_IIcadAttributeReference
#define IID_IAcadAttributeReferences			IID_IIcadAttributeReferences
#define IID_IAcadBlockReference					IID_IIcadBlockReference
#define IID_IAcadCircle							IID_IIcadCircle
#define IID_IAcadEllipse						IID_IIcadEllipse
#define IID_IAcadHatch							IID_IIcadHatch
#define IID_IAcadLeader							IID_IIcadLeader
#define IID_IAcadLine							IID_IIcadLine
#define IID_IAcadLightWeightPolyline			IID_IIcadLightWeightPolyline
#define IID_IAcadMText							IID_IIcadMText
#define IID_IAcadPointEntity					IID_IIcadPointEntity
#define IID_IAcadPolyline						IID_IIcadPolyline
#define IID_IAcadPolygonMesh					IID_IIcadPolygonMesh
#define IID_IAcadPolyfaceMesh					IID_IIcadPolyfaceMesh
#define IID_IAcadPViewport						IID_IIcadPViewport
#define IID_IAcadRasterImage					IID_IIcadRasterImage
#define IID_IAcadRay							IID_IIcadRay
#define IID_IAcadShape							IID_IIcadShape
#define IID_IAcadSolid							IID_IIcadSolid
#define IID_IAcadSpline							IID_IIcadSpline
#define IID_IAcadText							IID_IIcadText
#define IID_IAcadTolerance						IID_IIcadTolerance
#define IID_IAcadTrace							IID_IIcadTrace
#define IID_IAcadXline							IID_IIcadXline
#define IID_IAcadExternalReference				IID_IIcadExternalReference
#define IID_IAcadRegion							IID_IIcadRegion
#define IID_IAcadMLine							IID_IIcadMLine
#define IID_IAcadOle							IID_IIcadOle
#define IID_IAcad3DSolid						IID_IIcad3DSolid
#define IID_IAcadDimension						IID_IIcadDimension
#define IID_IAcadDimAngular						IID_IIcadDimAngular
#define IID_IAcadDimAligned						IID_IIcadDimAligned
#define IID_IAcadDimDiametric					IID_IIcadDimDiametric
#define IID_IAcadDimOrdinate					IID_IIcadDimOrdinate
#define IID_IAcadDimRadial						IID_IIcadDimRadial
#define IID_IAcadDimRotated						IID_IIcadDimRotated
#define IID_IAcadDim3PointAngular				IID_IIcadDim3PointAngular
#define IID_IAcadModelSpace						IID_IIcadModelSpace
#define IID_IAcadPaperSpace						IID_IIcadPaperSpace
#define IID_IAcadDocument						IID_IIcadDocument
#define DIID__DAcadDocumentEvents				DIID__EIcadDocument //?
#define IID_IAcadDatabasePreferences			IID_IIcadDatabasePreferences
#define LIBID_AutoCAD							LIBID_ZwCAD

//CLSIDs:

#define  CLSID_AcadDimension					CLSID_ZwcadDimension
#define  CLSID_AcadDimAngular					CLSID_ZwcadDimAngular
#define  CLSID_AcadDimAligned					CLSID_ZwcadDimAligned
#define  CLSID_AcadDimDiametric					CLSID_ZwcadDimDiametric
#define  CLSID_AcadDimOrdinate					CLSID_ZwcadDimOrdinate
#define  CLSID_AcadDimRadial					CLSID_ZwcadDimRadial
#define  CLSID_AcadDimRotated					CLSID_ZwcadDimRotated
#define  CLSID_AcadDim3PointAngular				CLSID_ZwcadDim3PointAngular
#define  CLSID_AcadModelSpace					CLSID_ZwcadModelSpace
#define  CLSID_AcadPaperSpace					CLSID_ZwcadPaperSpace
#define  CLSID_AcadDocument						CLSID_ZwcadDocument
#define  CLSID_AcadDatabasePreferences			CLSID_ZwcadDatabasePreferences
#define  CLSID_AcadEntity						CLSID_ZwcadEntity
#define  CLSID_Acad3DFace						CLSID_Zwcad3DFace
#define  CLSID_Acad3DPolyline					CLSID_Zwcad3DPolyline
#define  CLSID_AcadArc							CLSID_ZwcadArc
#define  CLSID_AcadAttribute					CLSID_ZwcadAttribute
#define  CLSID_AcadAttributeReference			CLSID_ZwcadAttributeReference
#define  CLSID_AcadAttributeReferences			CLSID_ZwcadAttributeReferences
#define  CLSID_AcadBlockReference				CLSID_ZwcadBlockReference
#define  CLSID_AcadCircle						CLSID_ZwcadCircle
#define  CLSID_AcadEllipse						CLSID_ZwcadEllipse
#define  CLSID_AcadHatch						CLSID_ZwcadHatch
#define  CLSID_AcadLeader						CLSID_ZwcadLeader
#define  CLSID_AcadLine							CLSID_ZwcadLine
#define  CLSID_AcadLWPolyline					CLSID_ZwcadLWPolyline
#define  CLSID_AcadMText						CLSID_ZwcadMText
#define  CLSID_AcadPointEntity					CLSID_ZwcadPointEntity
#define  CLSID_AcadPolyline						CLSID_ZwcadPolyline
#define  CLSID_AcadPolygonMesh					CLSID_ZwcadPolygonMesh
#define  CLSID_AcadPolyfaceMesh					CLSID_ZwcadPolyfaceMesh
#define  CLSID_AcadPViewport					CLSID_ZwcadPViewport
#define  CLSID_AcadRasterImage					CLSID_ZwcadRasterImage
#define  CLSID_AcadRay							CLSID_ZwcadRay
#define  CLSID_AcadShape						CLSID_ZwcadShape
#define  CLSID_AcadSolid						CLSID_ZwcadSolid
#define  CLSID_AcadSpline						CLSID_ZwcadSpline
#define  CLSID_AcadText							CLSID_ZwcadText
#define  CLSID_AcadTolerance					CLSID_ZwcadTolerance
#define  CLSID_AcadTrace						CLSID_ZwcadTrace
#define  CLSID_AcadXline						CLSID_ZwcadXline
#define  CLSID_AcadExternalReference			CLSID_ZwcadExternalReference
#define  CLSID_AcadDocuments					CLSID_ZwcadDocuments
#define  CLSID_AcadWindows						CLSID_ZwcadWindows
#define  CLSID_AcadWindow						CLSID_ZwcadWindow
#define  CLSID_AcadApplication					CLSID_ZwcadApplication
#define  CLSID_AcadWorkspace					CLSID_ZwcadWorkspace
#define  CLSID_AcadApplicationPreferences		CLSID_ZwcadApplicationPreferences
#define  CLSID_AcadPoint						CLSID_ZwcadPoint
#define  CLSID_AcadPoints						CLSID_ZwcadPoints
#define  CLSID_AcadVector						CLSID_ZwcadVector
#define  CLSID_AcadMatrix						CLSID_ZwcadMatrix
#define  CLSID_AcadLibrary						CLSID_ZwcadLibrary
#define  CLSID_AcadUtility						CLSID_ZwcadUtility
#define  CLSID_AcadRegisteredApplication		CLSID_ZwcadRegisteredApplication
#define  CLSID_AcadRegisteredApplications		CLSID_ZwcadRegisteredApplications
#define  CLSID_AcadBlock						CLSID_ZwcadBlock
#define  CLSID_AcadBlocks						CLSID_ZwcadBlocks
#define  CLSID_AcadDimStyle						CLSID_ZwcadDimStyle
#define  CLSID_AcadDimStyles					CLSID_ZwcadDimStyles
#define  CLSID_AcadLayer						CLSID_ZwcadLayer
#define  CLSID_AcadLayers						CLSID_ZwcadLayers
#define  CLSID_AcadLinetype						CLSID_ZwcadLinetype
#define  CLSID_AcadLinetypes					CLSID_ZwcadLinetypes
#define  CLSID_AcadTextStyle					CLSID_ZwcadTextStyle
#define  CLSID_AcadTextStyles					CLSID_ZwcadTextStyles
#define  CLSID_AcadUCS							CLSID_ZwcadUCS
#define  CLSID_AcadUCSs							CLSID_ZwcadUCSs
#define  CLSID_AcadView							CLSID_ZwcadView
#define  CLSID_AcadViews						CLSID_ZwcadViews
#define  CLSID_AcadViewport						CLSID_ZwcadViewport
#define  CLSID_AcadViewports					CLSID_ZwcadViewports
#define  CLSID_AcadSelectionSet					CLSID_ZwcadSelectionSet
#define  CLSID_AcadSelectionSets				CLSID_ZwcadSelectionSets
#define  CLSID_AcadPlotterPen					CLSID_ZwcadPlotterPen
#define  CLSID_AcadPlotterPens					CLSID_ZwcadPlotterPens
#define  CLSID_AcadPlotProperties				CLSID_ZwcadPlotProperties
#define  CLSID_AcadPlotManager					CLSID_ZwcadPlotManager
#define  CLSID_AcadGroup						CLSID_ZwcadGroup
#define  CLSID_AcadGroups						CLSID_ZwcadGroups
#define  CLSID_AcadRegion						CLSID_ZwcadRegion
#define  CLSID_AcadMLine						CLSID_ZwcadMLine
#define  CLSID_AcadXRecord						CLSID_ZwcadXRecord
#define  CLSID_AcadDictionary					CLSID_ZwcadDictionary
#define  CLSID_AcadDictionaries					CLSID_ZwcadDictionaries
#define  CLSID_AcadState						CLSID_ZwcadState
#define  CLSID_AcadHyperlinks					CLSID_ZwcadHyperlinks
#define  CLSID_AcadHyperlink					CLSID_ZwcadHyperlink
#define  CLSID_AcadPlotConfiguration			CLSID_ZwcadPlotConfiguration
#define  CLSID_AcadPlotConfigurations			CLSID_ZwcadPlotConfigurations
#define  CLSID_AcadLayout						CLSID_ZwcadLayout
#define  CLSID_AcadLayouts						CLSID_ZwcadLayouts
#define  CLSID_AcadPlot							CLSID_ZwcadPlot
#define  CLSID_AcadSummaryInfo					CLSID_ZwcadSummaryInfo
#define  CLSID_AcadSortentsTable				CLSID_ZwcadSortentsTable
#define  CLSID_AcadOle							CLSID_ZwcadOle
#define  CLSID_AcadAcCmColor					CLSID_ZwcadAcCmColor
#define  CLSID_Acad3DSolid						CLSID_Zwcad3DSolid
#define  CLSID_AcadMenuBar						CLSID_ZwcadMenuBar
#define  CLSID_AcadMenuGroups					CLSID_ZwcadMenuGroups
#define  CLSID_AcadMenuGroup					CLSID_ZwcadMenuGroup
#define  CLSID_AcadPopupMenus					CLSID_ZwcadPopupMenus
#define  CLSID_AcadPopupMenu					CLSID_ZwcadPopupMenu
#define  CLSID_AcadPopupMenuItem				CLSID_ZwcadPopupMenuItem
#define  CLSID_AcadToolbars						CLSID_ZwcadToolbars
#define  CLSID_AcadToolbar						CLSID_ZwcadToolbar
#define  CLSID_AcadToolbarItem					CLSID_ZwcadToolbarItem


#endif

