
#ifndef _ARXPORT_AD_ACDB_H_
#define _ARXPORT_AD_ACDB_H_ 1

#include "adesk.h"
#include "AdAChar.h"
#include "rxobject.h"
#include "gepnt3d.h"

#ifdef ACAD_OBJID_INLINE_INTERNAL
#include "dbidinln.h"
#else
#include "dbidapps.h"
#endif

#include "dbboiler.h"

#include "acadstrc.h"
#include "..\inc\zcdb.h"

typedef ZcDb AcDb;

#define AcDbDwgVersion						ZcDbDwgVersion
#define ACDB_SERVICES						ZCDB_SERVICES               
#define ACDB_MODEL_SPACE					ZCDB_MODEL_SPACE            
#define ACDB_PAPER_SPACE					ZCDB_PAPER_SPACE            
#define ACDB_NULL_HANDLE					ZCDB_NULL_HANDLE            
#define ACDB_BROKEN_HANDLE					ZCDB_BROKEN_HANDLE          
#define ACDB_OPEN_BRACE_STR					ZCDB_OPEN_BRACE_STR         
#define ACDB_OPEN_BRACE_CHAR				ZCDB_OPEN_BRACE_CHAR        
#define ACDB_CLOSE_BRACE_STR				ZCDB_CLOSE_BRACE_STR        
#define ACDB_CLOSE_BRACE_CHAR				ZCDB_CLOSE_BRACE_CHAR       
#define ACDB_GROUP_DICTIONARY				ZCDB_GROUP_DICTIONARY       
#define ACDB_MLINESTYLE_DICTIONARY			ZCDB_MLINESTYLE_DICTIONARY  
#define ACDB_LAYOUT_DICTIONARY				ZCDB_LAYOUT_DICTIONARY      
#define ACDB_PLOTSETTINGS_DICTIONARY		ZCDB_PLOTSETTINGS_DICTIONARY
#define ACDB_PLOTSTYLENAME_DICTIONARY		ZCDB_PLOTSTYLENAME_DICTIONAR
#define ACDB_MATERIAL_DICTIONARY			ZCDB_MATERIAL_DICTIONARY    
#define ACDB_COLOR_DICTIONARY				ZCDB_COLOR_DICTIONARY       
#define ACDB_TABLESTYLE_DICTIONARY			ZCDB_TABLESTYLE_DICTIONARY  
#define ACDB_EMBEDDED_OBJECT_STR			ZCDB_EMBEDDED_OBJECT_STR    
#define ACDB_LAYERSTATES_DICTIONARY			ZCDB_LAYERSTATES_DICTIONARY 
#define ACDB_FIELD_DICTIONARY				ZCDB_FIELD_DICTIONARY       
#define ACDB_FIELDLIST_DICTIONARY			ZCDB_FIELDLIST_DICTIONARY   
#define ACDB_ENHANCED_BLOCK					ZCDB_ENHANCED_BLOCK         
#define ACDB_ENHANCED_BLOCK_EVALKEY			ZCDB_ENHANCED_BLOCK_EVALKEY 
#define ACDB_ENHANCED_BLOCK_REF				ZCDB_ENHANCED_BLOCK_REF     
#define ACDB_SECTION_MANAGER				ZCDB_SECTION_MANAGER
#define ACDB_DATALINK						ZCDB_DATALINK
#define ACDB_ANNOTATIONSCALES_COLLECTION	ZCDB_ANNOTATIONSCALES_COLLECTION
#define ACDB_MLEADERSTYLE_DICTIONARY		ZCDB_MLEADERSTYLE_DICTIONARY

#endif
