
#ifndef _ARXPORT_AD_ACEDADS_H_
#define _ARXPORT_AD_ACEDADS_H_ 1

#include "adsdef.h"
#include "acmem.h"
#include "AdAChar.h"
#include "..\inc\zcedzds.h"

#define acrx_abort						zcrx_abort
#define acedGetAppName					zcedGetAppName
#define acedUpdate						zcedUpdate
#define adsw_acadMainWnd				zdsw_zcadMainWnd
#ifndef adsw_hwndAcad
#define adsw_hwndAcad					adsw_acadMainWnd()
#endif
#define adsw_acadDocWnd					zdsw_zcadDocWnd
#define acedCommand						zcedCommand
#define acedCmd							zcedCmd
#define acedRegFunc						zcedRegFunc
#define acedUsrBrk						zcedUsrBrk
#define acedDefun						zcedDefun
#define acedSetFunHelp					zcedSetFunHelp
#define acedUndef						zcedUndef
#define acedGetFunCode					zcedGetFunCode
#define acedGetArgs						zcedGetArgs
#define acedRetList						zcedRetList
#define acedRetVal						zcedRetVal
#define acedRetPoint					zcedRetPoint
#define acedRetStr						zcedRetStr
#define acedRetName						zcedRetName
#define acedRetInt						zcedRetInt
#define acedRetReal						zcedRetReal
#define acedRetT						zcedRetT
#define acedRetNil						zcedRetNil
#define acedRetVoid						zcedRetVoid
#define acedEntSel						zcedEntSel
#define acedNEntSel						zcedNEntSel
#define acedNEntSelP					zcedNEntSelP
#define acedSSGet						zcedSSGet
#define acedSSGetFirst					zcedSSGetFirst
#define acedSSSetFirst					zcedSSSetFirst
#define acedSSFree						zcedSSFree
#define acedSSLength					zcedSSLength
#define acedSSAdd						zcedSSAdd
#define acedSSDel						zcedSSDel
#define acedSSMemb						zcedSSMemb
#define acedSSName						zcedSSName
#define acedSSNameX						zcedSSNameX
#define acedSSGetKwordCallbackPtr		zcedSSGetKwordCallbackPtr
#define acedSSSetKwordCallbackPtr		zcedSSSetKwordCallbackPtr
#define acedSSGetOtherCallbackPtr		zcedSSGetOtherCallbackPtr
#define acedSSSetOtherCallbackPtr		zcedSSSetOtherCallbackPtr
#define acedTrans						zcedTrans
#define acedSetVar						zcedSetVar
#define acedInitGet						zcedInitGet
#define acedGetSym						zcedGetSym
#define acedPutSym						zcedPutSym
#define acedHelp						zcedHelp
#define acedFNSplit						zcedFNSplit
#define acedArxLoaded					zcedZrxLoaded
#define acedArxLoad						zcedZrxLoad
#define acedArxUnload					zcedZrxUnload
#define acedInvoke						zcedInvoke
#define acedGetVar						zcedGetVar
#define acedFindFile					zcedFindFile
#define acedGetEnv						zcedGetEnv
#define acedSetEnv						zcedSetEnv
#define acedGetCfg						zcedGetCfg
#define acedSetCfg						zcedSetCfg
#define acedGetString					zcedGetString
#define acedGetStringB					zcedGetStringB
#define acedMenuCmd						zcedMenuCmd
#define acedPrompt						zcedPrompt
#define acedAlert						zcedAlert
#define acedGetAngle					zcedGetAngle
#define acedGetCorner					zcedGetCorner
#define acedGetDist						zcedGetDist
#define acedGetOrient					zcedGetOrient
#define acedGetPoint					zcedGetPoint
#define acedGetInt						zcedGetInt
#define acedGetKword					zcedGetKword
#define acedGetReal						zcedGetReal
#define acedGetInput					zcedGetInput
#define acedVports						zcedVports
#define acedTextScr						zcedTextScr
#define acedGraphScr					zcedGraphScr
#define acedTextPage					zcedTextPage
#define acedRedraw						zcedRedraw
#define acedOsnap						zcedOsnap
#define acedGrRead						zcedGrRead
#define acedGrText						zcedGrText
#define acedGrDraw						zcedGrDraw
#define acedGrVecs						zcedGrVecs
#define acedXformSS						zcedXformSS
#define acedDragGen						zcedDragGen
#define acedSetView						zcedSetView
#define acedGetFileD					zcedGetFileD
#define acedGetFileNavDialog			zcedGetFileNavDialog
#define acedTextBox						zcedTextBox
#define acedTablet						zcedTablet
#define acedGetCName					zcedGetCName
#define acedEatCommandThroat			zcedEatCommandThroat
#define acdbEntDel						zcdbEntDel
#define acdbEntGetX						zcdbEntGetX
#define acdbEntGet						zcdbEntGet
#define acdbEntLast						zcdbEntLast
#define acdbEntNext						zcdbEntNext
#define acdbEntUpd						zcdbEntUpd
#define acdbEntMod						zcdbEntMod
#define acdbEntMake						zcdbEntMake
#define acdbEntMakeX					zcdbEntMakeX
#define acdbRegApp						zcdbRegApp
#define acdbTblNext						zcdbTblNext
#define acdbTblSearch					zcdbTblSearch
#define acdbNamedObjDict				zcdbNamedObjDict
#define acdbDictSearch					zcdbDictSearch
#define acdbDictNext					zcdbDictNext
#define acdbDictRename					zcdbDictRename
#define acdbDictRemove					zcdbDictRemove
#define acdbDictAdd						zcdbDictAdd
#define acdbTblObjName					zcdbTblObjName
#define acdbAngToS						zcdbAngToS
#define acdbRawAngToS					zcdbRawAngToS
#define acdbRToS						zcdbRToS
#define acdbAngToF						zcdbAngToF
#define acdbRawAngToF					zcdbRawAngToF
#define acdbDisToF						zcdbDisToF
#define acdbInters						zcdbInters
#define acdbSNValid						zcdbSNValid
#define acedGetFullInput				zcedGetFullInput
#define acedGetFullKword				zcedGetFullKword
#define acedGetFullString				zcedGetFullString
#define acedSSNameXEx					zcedSSNameXEx
#define acedArxLoad						zcedZrxLoad
#define acedArxLoaded					zcedZrxLoaded
#define acedArxUnload					zcedZrxUnload
#define ads_queueexpr					zcedQueueExpr

#endif
