
#ifndef _ARXPORT_AD_ACSTATUSBAR_H_
#define _ARXPORT_AD_ACSTATUSBAR_H_ 1

#include "acdocman.h"
#include "..\inc\zcstatusbar.h"


#define ACSB_NOBORDERS  (1<<0)
#define ACSB_POPOUT     (1<<1)
#define ACSB_STRETCH    (1<<2)
#define ACSB_NORMAL     (1<<3)
#define ACSB_COMMAND    (1<<4)
#define ACSB_POPUP      (1<<5)

typedef ZcStatusBarItem					AcStatusBarItem;
typedef ZcPane							AcPane;
typedef ZcTrayItemAnimationControl		AcTrayItemAnimationControl;
typedef ZcTrayItemBubbleWindowControl	AcTrayItemBubbleWindowControl;
typedef ZcTrayItem						AcTrayItem;
typedef ZcApStatusBar					AcApStatusBar;
typedef ZcStatusBarMenuItem				AcStatusBarMenuItem;

#define AcDefaultPane						ZcDefaultPane

#define ACSBPANE_APP_MODEMACRO				ZCSBPANE_APP_MODEMACRO
#define ACSBPANE_APP_CURSORCOORD			ZCSBPANE_APP_CURSORCOORD
#define ACSBPANE_APP_SNAP					ZCSBPANE_APP_SNAP
#define ACSBPANE_APP_GRID					ZCSBPANE_APP_GRID
#define ACSBPANE_APP_ORTHO					ZCSBPANE_APP_ORTHO
#define ACSBPANE_APP_POLAR					ZCSBPANE_APP_POLAR
#define ACSBPANE_APP_OTRACK					ZCSBPANE_APP_OTRACK
#define ACSBPANE_APP_LINEWEIGHT				ZCSBPANE_APP_LINEWEIGHT
#define ACSBPANE_APP_PAPERMODEL				ZCSBPANE_APP_PAPERMODEL
#define ACSBPANE_APP_PAPER					ZCSBPANE_APP_PAPER
#define ACSBPANE_APP_MODEL					ZCSBPANE_APP_MODEL
#define ACSBPANE_APP_OSNAP					ZCSBPANE_APP_OSNAP
#define ACSBPANE_APP_FLOAT					ZCSBPANE_APP_FLOAT
#define ACSBPANE_APP_TABLET					ZCSBPANE_APP_TABLET
#define	ACSBPANE_APP_SPACER					ZCSBPANE_APP_SPACER
#define ACSBPANE_APP_VPMAX_PREV				ZCSBPANE_APP_VPMAX_PREV
#define ACSBPANE_APP_VPMAX					ZCSBPANE_APP_VPMAX
#define ACSBPANE_APP_VPMAX_NEXT				ZCSBPANE_APP_VPMAX_NEXT
#define ACSBPANE_APP_DYNINPUT				ZCSBPANE_APP_DYNINPUT
#define ACSBPANE_APP_DYNAMICUCS				ZCSBPANE_APP_DYNAMICUCS
#define ACSBPANE_APP_LAYOUTMODELICONS		ZCSBPANE_APP_LAYOUTMODELICONS
#define ACSBPANE_APP_MODEL_ICON				ZCSBPANE_APP_MODEL_ICON
#define ACSBPANE_APP_LAYOUT_ICON			ZCSBPANE_APP_LAYOUT_ICON
#define ACSBPANE_APP_LAYOUTMORE_ICON		ZCSBPANE_APP_LAYOUTMORE_ICON

#define ACSBPANE_APP_ALL					ZCSBPANE_APP_ALL
#define ACSBPANE_ANNO_STRETCH				ZCSBPANE_ANNO_STRETCH
#define ACSBPANE_ANNO_AUTOSCALE				ZCSBPANE_ANNO_AUTOSCALE
#define ACSBPANE_ANNO_VIEWPORT_SCALE_LABEL	ZCSBPANE_ANNO_VIEWPORT_SCALE_LABEL
#define ACSBPANE_ANNO_VIEWPORT_SCALE		ZCSBPANE_ANNO_VIEWPORT_SCALE
#define ACSBPANE_ANNO_VIEWPORT_LOCK_STATE	ZCSBPANE_ANNO_VIEWPORT_LOCK_STATE
#define ACSBPANE_ANNO_ANNOTATION_SCALE_LABEL ZCSBPANE_ANNO_ANNOTATION_SCALE_LABEL
#define ACSBPANE_ANNO_ANNOTATION_SCALE		ZCSBPANE_ANNO_ANNOTATION_SCALE
#define ACSBPANE_ANNO_ANNO_ALL_VISIBLE		ZCSBPANE_ANNO_ANNO_ALL_VISIBLE
#define ACSBPANE_ANNO_EMPTY					ZCSBPANE_ANNO_EMPTY


#endif