#ifndef _ARXPORT_ACTCUICATALOGVIEWITEM_H_
#define _ARXPORT_ACTCUICATALOGVIEWITEM_H_ 1

#include "AcTc.h"
#include "AcTcUi.h"


class CZcTcUiCatalogView;
typedef CZcTcUiCatalogView  CAcTcUiCatalogView;

#include "..\inc\ZcTcUiCatalogViewItem.h"

#define ACTCUI_CVISTYLE_PUSHBUTTON      ZCTCUI_CVISTYLE_PUSHBUTTON

#define ACTCUI_CVISTYLE_SHOWTEXT        ZCTCUI_CVISTYLE_SHOWTEXT

#define ACTCUI_CVISTYLE_RIGHTTEXT       ZCTCUI_CVISTYLE_RIGHTTEXT

#define ACTCUI_CVISTYLE_FLYOUT          ZCTCUI_CVISTYLE_FLYOUT

#define ACTCUI_CVISTYLE_FULLROW         ZCTCUI_CVISTYLE_FULLROW

#define ACTCUI_CVISTYLE_HIDEIMAGE       ZCTCUI_CVISTYLE_HIDEIMAGE

#define ACTCUI_CVISTYLE_TEXT            ZCTCUI_CVISTYLE_TEXT

#define ACTCUI_CVISTYLE_SEPARATOR       ZCTCUI_CVISTYLE_SEPARATOR

#define ACTCUI_CVISTATE_HIGHLIGHTED     ZCTCUI_CVISTATE_HIGHLIGHTED

#define ACTCUI_CVISTATE_SELECTED        ZCTCUI_CVISTATE_SELECTED

#define ACTCUI_CVISTATE_HALO            ZCTCUI_CVISTATE_HALO

#define ACTCUI_CVISTATE_FOCUSED         ZCTCUI_CVISTATE_FOCUSED


#define ACTCUI_CVIR_BOUNDS              ZCTCUI_CVIR_BOUNDS
#define ACTCUI_CVIR_IMAGE               ZCTCUI_CVIR_IMAGE
#define ACTCUI_CVIR_LABEL               ZCTCUI_CVIR_LABEL
#define ACTCUI_CVIR_USEFULLLABEL        ZCTCUI_CVIR_USEFULLLABEL
#define ACTCUI_CVIR_TRIGGER             ZCTCUI_CVIR_TRIGGER
#define ACTCUI_CVIR_WORLDRECT           ZCTCUI_CVIR_WORLDRECT

typedef CZcTcUiCatalogViewItem          CAcTcUiCatalogViewItem;  

#define CAcTcUiCatalogViewItemArray     CZcTcUiCatalogViewItemArray

#endif