#ifndef _ARXPORT_ADUIMESSAGE_H_
#define _ARXPORT_ADUIMESSAGE_H_ 1


#include "..\inc\zduiDropTarget.h"

#define UM_ADUI_DRAGENTER   UM_ZDUI_DRAGENTER
#define UM_ADUI_DRAGOVER    UM_ZDUI_DRAGOVER
#define UM_ADUI_DRAGLEAVE   UM_ZDUI_DRAGLEAVE
#define UM_ADUI_DROP        UM_ZDUI_DROP
#define UM_ADUI_DROPEX      UM_ZDUI_DROPEX
#define UM_ADUI_DRAGSCROLL  UM_ZDUI_DRAGSCROLL

typedef  tagZDUI_DRAGDATA tagADUI_DRAGDATA;
typedef  ZDUI_DRAGDATA    ADUI_DRAGDATA;
typedef  PZDUI_DRAGDATA   PADUI_DRAGDATA;
typedef  CZdUiDropTarget  CAdUiDropTarget;

#endif
