#ifndef _ARXPORT_ADUIGROUPCTRL_H_
#define _ARXPORT_ADUIGROUPCTRL_H_ 1


#include "..\inc\zduiGroupCtrl.h"

typedef ZdUiBmpBtnFcnPtr       AdUiBmpBtnFcnPtr;
typedef ZdUiGroupCtrlData      AdUiGroupCtrlData;

typedef ZDUIGROUPCTRLDATALIST  ADUIGROUPCTRLDATALIST;

typedef ZdUiBmpBtnData         AdUiBmpBtnData;

typedef ZDUIHEADERBTNLIST      ADUIHEADERBTNLIST;



#define ADUI_NCHT_BASE                       ZDUI_NCHT_BASE 
#define ADUI_NCHT_TITLE                      ZDUI_NCHT_TITLE
#define ADUI_NCHT_CHEVRON                    ZDUI_NCHT_CHEVRON
#define ADUI_NCHT_BUTTON                     ZDUI_NCHT_BUTTON 


#define ADUI_GROUP_BORDER_SIZE               ZDUI_GROUP_BORDER_SIZE
#define ADUI_GROUP_TITLE_HEIGHT              ZDUI_GROUP_TITLE_HEIGHT
#define ADUI_GROUP_TITLE_BEVELSIZE           ZDUI_GROUP_TITLE_BEVELSIZE
#define ADUI_GROUP_TITLE_TEXTLEFT            ZDUI_GROUP_TITLE_TEXTLEFT
#define ADUI_GROUP_TITLE_TEXTTOP             ZDUI_GROUP_TITLE_TEXTTOP
#define ADUI_GROUP_BUTTON_SIZE               ZDUI_GROUP_BUTTON_SIZE
#define ADUI_GROUP_BUTTONS_RIGHT             ZDUI_GROUP_BUTTONS_RIGHT
#define ADUI_GROUP_BUTTON_TOPPADDING         ZDUI_GROUP_BUTTON_TOPPADDING
#define ADUI_GROUP_BUTTON_BOTTOMPADDING      ZDUI_GROUP_BUTTON_BOTTOMPADDING
#define ADUI_GROUP_BUTTON_SPACE              ZDUI_GROUP_BUTTON_SPACE
#define ADUI_GROUP_CHEVRON_RIGHT             ZDUI_GROUP_CHEVRON_RIGHT
#define ADUI_GROUP_CHILD_VERT_SPACE          ZDUI_GROUP_CHILD_VERT_SPACE


#define ADUI_GROUP_STYLE_CHEVRON             ZDUI_GROUP_STYLE_CHEVRON
#define ADUI_GROUP_STYLE_SHOWBTNFORCE        ZDUI_GROUP_STYLE_SHOWBTNFORCE
#define ADUI_GROUP_STYLE_NONACTIVE           ZDUI_GROUP_STYLE_NONACTIVE


#define WM_ADUI_VISIBILITY_CHANGING    WM_ZDUI_VISIBILITY_CHANGING

typedef  CZdUiGroupCtrl CAdUiGroupCtrl;
#endif






