
#ifndef _ARXPORT_AD_DBXENTRYPOINT_H_
#define _ARXPORT_AD_DBXENTRYPOINT_H_ 1

#include "..\inc\zdbxEntryPoint.h"

#define ACDB_REGISTER_OBJECT_ENTRY_PRAGMA	ZCDB_REGISTER_OBJECT_ENTRY_PRAGMA
#define ACDB_REGISTER_OBJECT_ENTRY_AUTO		ZCDB_REGISTER_OBJECT_ENTRY_AUTO
#define acrxGetApp							zcrxGetApp
#define IMPLEMENT_ARX_ENTRYPOINT_CLR		IMPLEMENT_ZRX_ENTRYPOINT_CLR
#define IMPLEMENT_ARX_ENTRYPOINT			IMPLEMENT_ZRX_ENTRYPOINT


typedef ZcRxDbxApp			AcRxDbxApp;

#endif