
#ifndef AC_RXBOILER_H_
#define AC_RXBOILER_H_ 1

#include "rxnames.h"
#include "..\inc\zrxboiler.h"

#define ACRX_DECLARE_MEMBERS		ZCRX_DECLARE_MEMBERS
#define ACRX_DEFINE_MEMBERS			ZCRX_DEFINE_MEMBERS
#define ACRX_STATIC_CHECK			ZCRX_STATIC_CHECK
#define ACRX_NO_CONS_DEFINE_MEMBERS ZCRX_NO_CONS_DEFINE_MEMBERS
#define ACRX_CONS_DEFINE_MEMBERS	ZCRX_CONS_DEFINE_MEMBERS
#define ACRX_DXF_DEFINE_MEMBERS		ZCRX_DXF_DEFINE_MEMBERS

#endif
