
#ifndef _ARXPORT_RXNAMES_H_
#define _ARXPORT_RXNAMES_H_ 1

#include "..\inc\zrxnames.h"

#define ACRX_CLASS_DICTIONARY			ZCRX_CLASS_DICTIONARY
#define ACRX_DYNAMIC_LINKER				ZCRX_DYNAMIC_LINKER
#define ACRX_SERVICE_DICTIONARY			ZCRX_SERVICE_DICTIONARY
#define ACRX_KERNEL_SERVICES			ZCRX_KERNEL_SERVICES
#define ACRX_PROTOCOL_REACTOR_MANAGER	ZCRX_PROTOCOL_REACTOR_MANAGER

#endif
